name: Continuous Integration

# Controls when the action will run. 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install libcurl (Linux only)
        run: |
              if [ "$RUNNER_OS" == "Linux" ]; then
                sudo apt-get install -y libcurl4-openssl-dev
              fi
        shell: bash

      - name: Cache dependency builds
        uses: actions/cache@v1
        with:
          path: ~/.esy
          key: ${{ runner.OS }}-esy-dep-cache-${{ hashFiles('esy.lock/') }}
          restore-keys: |
            ${{ runner.OS }}-esy-dep-cache-
      
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install esy 0.6.10
        run: npm install --global esy@0.6.10

      - name: Install dependencies
        run: ./install-dependencies.sh
        shell: bash

      - name: Build library
        run: esy build

      - name: Run BasicExample
        run: esy '@examples' x BasicExample

      - name: Run tests
        run: esy '@tests' x TestRunner
